services:
  clubverse-db:
    image: postgres:15
    container_name: clubverse-db
    environment:
      POSTGRES_USER: clubuser
      POSTGRES_PASSWORD: clubpassword
      POSTGRES_DB: clubversedb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - clubverse-network

  redis:
    image: redis:alpine
    container_name: clubverse-redis
    ports:
      - "6379:6379"
    networks:
      - clubverse-network

  clubverse-backend:
    build:
      context: ./server
    container_name: clubverse-backend
    environment:
      PORT: 5000
      DB_USER: clubuser
      DB_PASSWORD: clubpassword
      DB_HOST: clubverse-db
      DB_PORT: 5432
      DB_NAME: clubversedb
      JWT_SECRET: supersecretclubversekey
      REDIS_URL: redis://redis:6379
    ports:
      - "5000:5000"
    depends_on:
      - clubverse-db
      - redis
    networks:
      - clubverse-network

  clubverse-frontend:
    build:
      context: .
    container_name: clubverse-frontend
    ports:
      - "3000:80"
    depends_on:
      - clubverse-backend
    networks:
      - clubverse-network

volumes:
  postgres_data:

networks:
  clubverse-network:
    driver: bridge
